version: '2'
services:

  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - mysql
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - code

  php:
    build: .
    working_dir: /var/www
    volumes_from:
      - code

  mysql:
    image: xtreamwayz/mysql
    ports:
      - "33061:3306"
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=docker

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./phpmyadmin.ini:/usr/local/etc/php/php.ini
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret

  code:
    image: busybox
    volumes:
      - ./www:/var/www

# COPY conf/my.cnf /etc/mysql/my.cnf
# - ./conf/php.ini:/etc/php/7.1/fpm/conf.d/40-custom.ini
# command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
